export const CARDS_FETCH_STARTED = "CARDS_FETCH_STARTED";
export const CARDS_FETCH_SUCCESS = "CARDS_FETCH_SUCCESS";
export const CARDS_FETCH_FAILED = "CARDS_FETCH_FAILED";

export const CARD_ADD_STARTED = "CARD_ADD_STARTED";
export const CARD_ADD_SUCCESS = "CARD_ADD_SUCCESS";
export const CARD_ADD_FAILED = "CARD_ADD_FAILED";

export const CARD_FETCH_SUCCESS = "CARD_FETCH_SUCCESS";
export const CARD_FETCH_FAILED = "CARD_FETCH_FAILED";

export const TRANS_FETCH_STARTED = "TRANS_FETCH_STARTED";
export const TRANS_FETCH_FAILED = "TRANS_FETCH_FAILED";
export const TRANS_FETCH_SUCCESS = "TRANS_FETCH_SUCCESS";

export const ACTIVE_CARD_CHANGED = "ACTIVE_CARD_CHANGED";

export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAILED = "PAYMENT_FAILED";
export const PAYMENT_REPEAT = "PAYMENT_REPEAT";
