// <auto-generated />
using System;
using AlfaBank.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlfaBank.WebApi.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20190625104636_ver1")]
    partial class ver1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlfaBank.Core.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardName")
                        .IsRequired();

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(19);

                    b.Property<int>("CardType");

                    b.Property<int>("Currency");

                    b.Property<DateTime>("DtOpenCard");

                    b.Property<int>("UserId");

                    b.Property<int>("ValidityYear");

                    b.HasKey("Id");

                    b.HasIndex("CardNumber");

                    b.HasIndex("UserId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardName = "my salary",
                            CardNumber = "4083969601038878",
                            CardType = 2,
                            Currency = 0,
                            DtOpenCard = new DateTime(2017, 6, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = 1,
                            ValidityYear = 3
                        },
                        new
                        {
                            Id = 2,
                            CardName = "my salary",
                            CardNumber = "6271195459697261",
                            CardType = 3,
                            Currency = 0,
                            DtOpenCard = new DateTime(2017, 6, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = 1,
                            ValidityYear = 3
                        },
                        new
                        {
                            Id = 3,
                            CardName = "my debt",
                            CardNumber = "4083969671288296",
                            CardType = 2,
                            Currency = 2,
                            DtOpenCard = new DateTime(2017, 6, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = 1,
                            ValidityYear = 3
                        },
                        new
                        {
                            Id = 4,
                            CardName = "for my family",
                            CardNumber = "5101266390203309",
                            CardType = 1,
                            Currency = 1,
                            DtOpenCard = new DateTime(2017, 6, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = 1,
                            ValidityYear = 3
                        },
                        new
                        {
                            Id = 5,
                            CardName = "my salary",
                            CardNumber = "4083961558623794",
                            CardType = 2,
                            Currency = 0,
                            DtOpenCard = new DateTime(2017, 6, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = 2,
                            ValidityYear = 3
                        },
                        new
                        {
                            Id = 6,
                            CardName = "my salary",
                            CardNumber = "6271196413417853",
                            CardType = 3,
                            Currency = 0,
                            DtOpenCard = new DateTime(2017, 6, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = 2,
                            ValidityYear = 3
                        },
                        new
                        {
                            Id = 7,
                            CardName = "my debt",
                            CardNumber = "4083967519051926",
                            CardType = 2,
                            Currency = 2,
                            DtOpenCard = new DateTime(2017, 6, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = 2,
                            ValidityYear = 3
                        },
                        new
                        {
                            Id = 8,
                            CardName = "for my family",
                            CardNumber = "5101265282206347",
                            CardType = 1,
                            Currency = 1,
                            DtOpenCard = new DateTime(2017, 6, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = 2,
                            ValidityYear = 3
                        });
                });

            modelBuilder.Entity("AlfaBank.Core.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardFromNumber");

                    b.Property<int>("CardId");

                    b.Property<string>("CardToNumber");

                    b.Property<DateTime>("DateTime");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(16, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardId = 1,
                            CardToNumber = "4083969601038878",
                            DateTime = new DateTime(2019, 6, 25, 13, 46, 36, 234, DateTimeKind.Local).AddTicks(3390),
                            Sum = 10m
                        },
                        new
                        {
                            Id = 2,
                            CardId = 2,
                            CardToNumber = "6271195459697261",
                            DateTime = new DateTime(2019, 6, 25, 13, 46, 36, 234, DateTimeKind.Local).AddTicks(7910),
                            Sum = 10m
                        },
                        new
                        {
                            Id = 3,
                            CardId = 3,
                            CardToNumber = "4083969671288296",
                            DateTime = new DateTime(2019, 6, 25, 13, 46, 36, 234, DateTimeKind.Local).AddTicks(7950),
                            Sum = 0.1376651982378854625550660793m
                        },
                        new
                        {
                            Id = 4,
                            CardId = 4,
                            CardToNumber = "5101266390203309",
                            DateTime = new DateTime(2019, 6, 25, 13, 46, 36, 235, DateTimeKind.Local).AddTicks(7890),
                            Sum = 0.1595405232929164007657945118m
                        },
                        new
                        {
                            Id = 5,
                            CardId = 5,
                            CardToNumber = "4083961558623794",
                            DateTime = new DateTime(2019, 6, 25, 13, 46, 36, 235, DateTimeKind.Local).AddTicks(7900),
                            Sum = 10m
                        },
                        new
                        {
                            Id = 6,
                            CardId = 6,
                            CardToNumber = "6271196413417853",
                            DateTime = new DateTime(2019, 6, 25, 13, 46, 36, 235, DateTimeKind.Local).AddTicks(7920),
                            Sum = 10m
                        },
                        new
                        {
                            Id = 7,
                            CardId = 7,
                            CardToNumber = "4083967519051926",
                            DateTime = new DateTime(2019, 6, 25, 13, 46, 36, 235, DateTimeKind.Local).AddTicks(7930),
                            Sum = 0.1376651982378854625550660793m
                        },
                        new
                        {
                            Id = 8,
                            CardId = 8,
                            CardToNumber = "5101265282206347",
                            DateTime = new DateTime(2019, 6, 25, 13, 46, 36, 235, DateTimeKind.Local).AddTicks(7930),
                            Sum = 0.1595405232929164007657945118m
                        });
                });

            modelBuilder.Entity("AlfaBank.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Birthday");

                    b.Property<string>("Firstname");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Surname");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserName");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "AQAAAAEAACcQAAAAEL5EJYCdN4s5drio+R0ZHNwBGdE32w9FmcYWRnorikhSQQ+DeLs1eA/AkMG9sUbY7w==",
                            UserName = "alice@alfabank.ru"
                        },
                        new
                        {
                            Id = 2,
                            Password = "AQAAAAEAACcQAAAAEOmCkrmo4bS4QMrbVf0j3t0/bmgfDW96E7yTnOJh8ZbTvshRgKf/cstvbtSHg49HxQ==",
                            UserName = "bob@alfabank.ru"
                        });
                });

            modelBuilder.Entity("AlfaBank.Core.Models.Card", b =>
                {
                    b.HasOne("AlfaBank.Core.Models.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AlfaBank.Core.Models.Transaction", b =>
                {
                    b.HasOne("AlfaBank.Core.Models.Card", "Card")
                        .WithMany("Transactions")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
